/*var ACELERACION_NAVE = 0.2; 
var LIMITE_VELOCIDAD_NAVE = 9; 
var TIEMPO_COLA_NAVE = 20;
var TIEMPO_MORIR = 3000;
var TIEMPO_MORIR_SKIN = 200;

var VELOCIDAD_ANGULO = 0.1;

var VELOCIDAD_DISPAROS = 10;
var TIEMPO_VELOCIDAD_DISPARO = 400;
var TIEMPO_DISPAROS_VIVOS = 2000;
var EXPLOSION_TIME = 800;

var EXPLOSION_TIME_BOMBA = 1200;

var TIEMPO_BOMBAS = 400;
var TIEMPO_EXPLOSION_BOMBAS = 400;*/

